zap:
  level: info
  format: console
  prefix: "[Cold2DB]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
dbConfig:
  dbPath:
  memConfig:
    memtableSize: 0
    memtableNums: 0
    memSpaceWaitTimeout: 0
    walDirPath:
    walSync: false
    walMMap: false
    indexerDir:
    indexerType: 0
  valueLogConfig:
    valueLogDir:
    valueLogFileSize: 0
    valueLogMmap: false
  indexConfig:
    indexerDir:
    indexerType: 0
  hardStateLogConfig:
    hardStateLogDir:
raftConfig:
  electionTick: 0
  heartbeatTick: 0
  nodes: []