zapConf:
  level: info
  format: console
  prefix: "[Cold2DB]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
dbConfig:
  dbPath: "/Users/hlhf/GolandProjects/Cold2DB/c2db"
  memConfig:
    memtableSize: 2048
    memtableNums: 10
    memSpaceWaitTimeout: 1
    walDirPath: "/Users/hlhf/GolandProjects/Cold2DB/c2db/wal"
    walSync: true
    walMMap: true
    indexerDir:
    indexerType: 0
  valueLogConfig:
    valueLogDir: "/Users/hlhf/GolandProjects/Cold2DB/c2db/vlog"
    valueLogFileSize: 0
    valueLogMmap: false
  indexConfig:
    indexerDir: "/Users/hlhf/GolandProjects/Cold2DB/c2db/index"
    indexerType: 0
  hardStateLogConfig:
    hardStateLogDir: "/Users/hlhf/GolandProjects/c2dbDB/raft"
raftConfig:
  electionTick: 100
  heartbeatTick: 100
  nodes: []